engines:
  duplication:
    enabled: true
    exclude_paths:
    - "Tests/"
    - "config/"
    - "src/config/"
    - "Database/Migrations"

    config:
      languages:
      - php

  fixme:
    enabled: true
    exclude_paths:
    - "Tests/"

  phpmd:
    enabled: true
    exclude_paths:
    - "Tests/"
    - "Database/Migrations"
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Design/CouplingBetweenObjects:
        enabled: false
      Naming/ShortVariable:
        enabled: false

ratings:
  paths:
  - "**.php"

exclude_paths:
  - "Tests/"
  - "**.md"
  - "**.json"
  - "**.xml"
